package com.example.springbootdemohelloworld.pojo;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.id
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.name
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_key
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    private String roleKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.description
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.create_time
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.update_time
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.id
     *
     * @return the value of tb_role.id
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.id
     *
     * @param id the value for tb_role.id
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.name
     *
     * @return the value of tb_role.name
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.name
     *
     * @param name the value for tb_role.name
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_key
     *
     * @return the value of tb_role.role_key
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public String getRoleKey() {
        return roleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_key
     *
     * @param roleKey the value for tb_role.role_key
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey == null ? null : roleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.description
     *
     * @return the value of tb_role.description
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.description
     *
     * @param description the value for tb_role.description
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.create_time
     *
     * @return the value of tb_role.create_time
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.create_time
     *
     * @param createTime the value for tb_role.create_time
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.update_time
     *
     * @return the value of tb_role.update_time
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.update_time
     *
     * @param updateTime the value for tb_role.update_time
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Tue Jan 23 11:40:03 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", roleKey=").append(roleKey);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}