server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.121.135:3306/spring_practice?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
    config:
      import:
        - nacos:nacos-config-example.properties?refresh=true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springbootdemohelloworld.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true


