spring:
  application:
    name: springboot_plugins
  kafka:
    bootstrap-servers: 192.168.137.100:9092
#    consumer:
#      auto-offset-reset: earliest
  elasticsearch:
    rest:
      uris: 192.168.137.100:9200

server:
  port: 8086